apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: graysonrichard/music-worker:v1
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: WORK_QUEUE
              value: "toWorker"
            - name: MINIO_HOST
              value: "minio:9000"
            - name: MINIO_USER
              value: "rootuser"
            - name: MINIO_PASSWD
              value: "rootpass123"
            - name: INPUT_BUCKET
              value: "queue"
            - name: OUTPUT_BUCKET
              value: "output"
            - name: DATA_DIR
              value: "/data"
          volumeMounts:
            - name: worker-data
              mountPath: /data
      volumes:
        - name: worker-data
          emptyDir: {}